site: Schneidy

url: http://schneidy.github.io
baseurl: 
production_url : schneidy.github.io

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
  


# # External gems
# plugins:
#   - jekyll-sitemap
#   - jekyll-mentions
#   - jemoji
#   - jekyll-redirect-from
#   - jekyll-feed
#   - jekyll-paginate
# # This is the default format. 
# # For more see: http://jekyllrb.com/docs/permalinks/
# permalink: /:categories/:year/:month/:day/:title 

# exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "/vendor/"]
# highlighter: rouge

# # Themes are encouraged to use these universal variables 
# # so be sure to set them if your theme uses them.
# #
# title: Dan Schneiderman
# subtitle: "Maker Consultant, Organizer, STEAM Advocate"
# email: schneiderman.daniel@gmail.com
# name: Dan Schneiderman
# author :
#   name : Dan Schneiderman
#   email : schneiderman.daniel@gmail.com
#   github : schneidy
#   twitter : hiteak
#   feedburner : feedname

# # The production_url is only used when full-domain names are needed
# # such as sitemap.txt 
# # Most places will/should use BASE_PATH to make the urls
# #
# # If you have set a CNAME (pages.github.com) set your custom domain here.
# # Else if you are pushing to username.github.io, replace with your username.
# # Finally if you are pushing to a GitHub project page, include the project name at the end.
# #
# production_url : schneidy.github.io
# baseurl: ''
# url: "http://schneidy.github.io"
# cover: "/assets/header_image.jpg"
# # logo: "/assets/logo.png"

# # Build settings
# markdown: kramdown
# paginate: 5
# paginate_path: "/page:num/"
# inter_post_navigation: false


# collections:
#   pages:
#     output: true
#     permalink: /:name
#   posts:
#     output: true
#     permalink: /blog/:slug
#   projects:
#     output: true
#     permalink: /project/:slug

# defaults:
#   -
#     scope:
#       path: ""
#     values:
#       layout: "default"
#   -
#     scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "page"
#   -
#     scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#   -
#     scope:
#       path: ""
#       type: "projects"
#     values:
#       layout: "project"

# markdown: kramdown

# kramdown:
#   input: GFM
#   syntax_highlighter: rouge
  
# sass:
#   style: compressed

# # Category descriptions (for archive pages)
# # descriptions:
# #   - cat: jekyll
# #     desc: "Posts describing Jekyll setup techniques."

# #   - cat: dummy
# #     desc: "Just some placeholder posts, lorem ipsum and the rest."



# # Social sharing protocols
# # These are for automatically generating sharing metadata for FB and Twitter
# # OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
# protocols:
#     fb_image: "/assets/logo.png"
#     fb_image_width: 612
#     fb_image_height: 605
#     fb_image_type: "image/png"

#     twitter_image: "/assets/logo.png"

#     os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
#     os_rcs_type: "git"
#     os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"

# ga_tracking_id: "UA-28086646-1"


